#!/usr/bin/env python

import os,sys
import requests
import json
from flask import Flask, request

@app.route('/webhook', methods=['GET'])
def verify():
    '''Respond to the webhook verification (GET request) by echoing back the challenge parameter.'''

    return request.args.get('challenge')

     
